name = "DualArrays"
uuid = "429e4e16-f749-45f3-beec-30742fae38ce"
version = "0.1.0"
authors = ["Sheehan Olver <solver@mac.com>"]

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
ChainRules = "1.72.6"
DiffRules = "1.15.1"
DifferentialEquations = "7.17.0"
ForwardDiff = "1.2.2"
Plots = "1.41.1"

[extras]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
dev = ["Revise"]
examples = ["Plots", "DifferentialEquations", "ForwardDiff", "BandedMatrices"]
test = ["Test", "ForwardDiff", "BandedMatrices"]
